### PR TITLE
Point to a newer version of cryptowat_exporter

### PR DESCRIPTION
**Pull request by nbarrientos**
It's probably a good idea to point users to a more recent version of the exporter. Older versions (including the one before the patch) had a default cache time that it was too short, consuming too fast the API allowance and getting users banned.

### CODE REVIEW

**Review by rauljordan — APPROVED** [review]

**Comment by rauljordan** [comment]
Hi @nbarrientos please sign our CLA in the comment above so we can merge this in

**Comment by rauljordan** [comment]
hy @nbarrientos friendly reminder to sign the claf

**Comment by rauljordan** [comment]
Closing due to inactivity

**Comment by nbarrientos** [comment]
¯\_(ツ)_/¯

**Pull request closed without merging**
