### PR TITLE
Add mirrors of the beaconcha.in explorer

### PR DESCRIPTION
**Pull request by nobd**
Open-source mirrors of bitfly's beaconcha.in explorer offering a free public API without rate limits, maintained by redot.com.

GitHub URLs:

https://github.com/nobd/ethscan-org
https://github.com/AtlantPlatform/eth2-redot-com

Our motivation to host these mirrors as a free community service with long-term commitment boils down to 3 key points:

1. If bitfly's beaconcha.in goes down for whatever reason there is just 1 explorer left in the world for eth2 which is closed source (beaconscan.com). We are not comfortable knowing this as eth2 validators and staking service operators.

2. bitfly's beaconcha.in offers paid APIs (https://beaconcha.in/pricing) you have to purchase not to hit essential rate limits which we believe is something hindering the eth2 ecosystem development - we got rid of paid APIs and any kind of rate limits in our explorer instances, i.e. APIs are available for free without limitations.

3. We have noticed sporadic delays in beaconcha.in explorer syncing to the latest slot, which we tried to address with HPC dedicated hardware running in DCs in 2 regions (EU and Asia). Additionally, we are working to improve the explorer backend logic to make our mirrors more stable & performant.

### CODE REVIEW

**Comment by nobd** [comment]
Hi @rauljordan, thanks for your feedback on my last PR! We have take the following steps as per your suggestion:

1. Retained bitfly's branding on both instances
2. Mentioned that it is a mirror maintained by Redot on both instances
3. Explicitly stated that this is a mirror of beaconcha.in in the PR itself

**Comment by Buttaa** [comment]
Please look into the official license on our repository. There are still a lot of things missing to fulfill the requirements.

**Comment by rauljordan** [comment]
Sorry @nobd but we decided to only list and endorse original projects. As such, we will not accept this PR

**Comment by nobd** [comment]
You’re doing a disservice to the Ethereum community with opaque rules and inconsistent impolite and incoherent replies which contradict logic and go against open-source ideology.

We were expressly asked by @rauljordan, to revert the mirrors which we hosted on our servers for everyone free of charge, to the original https://beaconcha.in logos, which we did promptly. Instead of posting our links, https://ethscan.org and https://eth2.redot.com, we were told that we are not GNU GPL 3 compliant. Our lawyers checked and reassured us that all is well, but in case it’s not very clear, please have a look https://choosealicense.com/licenses/gpl-3.0 and you will see in a user-friendly way that we are fully compliant. Then after we followed your instructions, you changed your mind for the third time.

What you’re doing goes against the spirit of openness and sharing as well as community support which we have tried to uphold. There is a lack of explorers for Ethereum 2.0 and running an exchange among other things, we faced this issue. By the way the original is written poorly, and keeps on introducing breaking changes, making it basically useless and impossible to use in practice, another reason for the fork. It is reasonable to assume that the entire community is facing this problem, and we tried to solve it. Instead of thanks, we were faced with arbitrarily made up and unsubstantiated claims, and when they were fully addressed, further arbitrary unsubstantiated claims – 3 times.

We propose that you either:

(1) Post our mirrors https://ethscan.org and https://eth2.redot.com
(2) Specify what we need to amend in a clear way so that you can post our sites https://ethscan.org and https://eth2.redot.com
(3) Clearly admit in a visible disclaimer, that you’re a biased resource, catering to interests of specific groups, and cite those groups, or just give them hearts back

**Comment by prestonvanloon** [comment]
@Buttaa Can you please follow up here on what explicit changes are required? 
@nobd has some good points that the ETH2 community could benefit from mirrored chain explorers. 
In the spirit of OSS, we should re-consider declining this request and accept it after redot has fulfilled whatever attribution requirements set forth by the terms / license of the beaconcha.in explorer.

**Comment by prestonvanloon** [comment]
I discussed this a bit more within our team and others privately.

Whether or not there is a technical compliance of GPLv3 from a legal interpretation is only part of the problem here. Bitfly is clearly unhappy with such a fork of the project with no links back to the original source. I looked around both of these mirror sites and neither of them have a path back to the original source. There is no copyright notice, no link to the forked github repository, and nothing along the lines of "A mirror of Bitfly's beaconcha.in". 

In Ethereum's open source community, we should support each other. If you want to provide an alternative beaconcha.in mirror so that users can have another option in the event that beaconcha.in goes down, then that is great and we can all appreciate this altruistic endeavor. While @prysmaticlabs is not the arbitrator of what should and should not exist in our open source community, we kindly ask that you clearly state some attribution to bitfly in your distributed websites. In return, we would accept this change in our documentation to list such mirrors.

**Comment by nobd** [comment]
Hi @prestonvanloon, actually we had all of the above: copyright notice, link to GitHub, note saying it's a mirror, we spent time making these changes per comments above. After requesting these changes, and they were executed, @rauljordan "changed his mind" and said it was not enough. If we get an explicit set of changes that me must make, and clear statement that this will cause listing of our mirrors we will implement them. Just don't want to waste time making changes again, if the goal is to arbitrarily make up things each time.

**Comment by prestonvanloon** [comment]
> actually we had all of the above: copyright notice, link to GitHub, note saying it's a mirror, we spent time making these changes per comments above. 

@nobd Could you point me to this information on your live websites? I couldn't find it anywhere on https://ethscan.org/ or https://eth2.redot.com/

As for explicit requirements, I previously mentioned that we would like to see ANY attribution to the original sources in your live website. There isn't even a link to your own github sources on the live sites. 

How about you add something in the footer, like this?
Screenshot from 2021-02-05 11-00-17

**Comment by Buttaa** [comment]
@nobd https://www.reddit.com/r/atlantio/comments/6yqka1/got_scammed/

Any updates on this?

**Comment by qu0b** [comment]
It would be great for @nobd and redot to be innovative and build something on top of our explorer, but from what I can see they are using our work to get publicity. The mirror is not being maintained - last commit 16 days ago and their version is slow and outdated. It would be great if they would build their own explorer or take ours as a basis and build upon it. Creating a mirror and not even maintaining it with our upstream branch is just a really bad user experience. Further, we would welcome contributions to improve our explorer, but this has not created any value for us or for the users.

**Comment by nobd** [comment]
@prestonvanloon is asking a reasonable question, and we are happy to oblige, and revert the site to a state which reflects explicit changes required to be posted in the community (we changed it after @rauljordan and @Buttaa started changing their demands on the go).

@buttaa 3 years ago someone tried to impersonate us (which is exactly what the reddit says). This happens with Etherscan almost every month for reference – we spent days with Google trying to shut these google ads down. As always, we’re happy to have an adult conversation, and would appreciate it if you not try to divert the conversation, if you don’t like the subject. We would appreciate it if you'd be civil and supportive.

@qu0b we are happy to maintain, and add features, and we're in the process of doing so, but this thread and attempt to silence us is a little distracting.

**Comment by nobd** [comment]
> > actually we had all of the above: copyright notice, link to GitHub, note saying it's a mirror, we spent time making these changes per comments above.
> 
> @nobd Could you point me to this information on your live websites? I couldn't find it anywhere on https://ethscan.org/ or https://eth2.redot.com/
> 
> As for explicit requirements, I previously mentioned that we would like to see ANY attribution to the original sources in your live website. There isn't even a link to your own github sources on the live sites.
> 
> How about you add something in the footer, like this?
> Screenshot from 2021-02-05 11-00-17

@prestonvanloon we have applied the proposed changes to both websites in question by adding references to beaconcha.in and GitHub repo with source:

image

**Comment by Buttaa** [comment]
> @Buttaa 3 years ago someone tried to impersonate us (which is exactly what the reddit says). This happens with Etherscan almost every month for reference – we spent days with Google trying to shut these google ads down. As always, we’re happy to have an adult conversation, and would appreciate it if you not try to divert the conversation, if you don’t like the subject. We would appreciate it if you'd be civil and supportive.

A simple google search returned more bad than good. I could link plenty of threads that point into the same direction. 
https://www.reddit.com/r/atlantio/comments/kxsqoq/this_was_one_of_the_smoothest_scams_in_crypto/

**Comment by nobd** [comment]
@Buttaa it's sad that you cling to a random negative thread, which just about any company has than behave like an adult. We could stoop to your level, but have higher standards at our firm.

More importantly, all requested edits were applied - @prestonvanloon please guide us when would you be able to accept this PR.

**Comment by rauljordan** [comment]
Hi @nobd thank you for adding proper attribution. There is no evidence of bad intentions in the mirrors. We confirm the links contain all necessary information and credit is given to Bitfly. We have included these explorers in a section called `Mirrors and Forks` in this pull request here: https://github.com/prysmaticlabs/documentation/pull/317.

**Comment by nobd** [comment]
Thanks @rauljordan @prestonvanloon - much appreciated. 

Hope we could eventually contribute more to ETH2 than just hosting these - working on our staking service to be more reliable & performant - @prestonvanloon special thanks for introducing experimental features like `attest-timely`, we're trying these out in the wild now to boost our validators' performance as we pass 100% of staking rewards to Redot clients atm.

**Pull request closed without merging**
