### PR TITLE
Major graphical documentation update

### PR DESCRIPTION
**Pull request by wgknowles**
Provides new logos and logical diagrams for most pages in the docs.
Original powerpoint file Prysm_Docs.pptx is also included for others to contribute.  All images were obtained with permission for commercial use without attribution.

### CODE REVIEW

**Comment by har00ga** [comment]
Left notes in Discord but adding them here for reference:

looking at the graphics rn, they look good :) the ones on the how prysm works pages are way too big, need to scale them down a muckload if they'll be used. for the validator sections, i like the graphics a lot, but I wonder if it may be better to integrate them into the how-prysm-works validator page and revamp the info instead, then link to it

the activation pages already throw a lot at the user, I think adding more graphics during that part may be overwhelming. but its certainly valuable information to have and clearly note

**Comment by wgknowles** [comment]
Scaled down the images on the "how prysm works" pages, and simplified the architecture page too. 
I reworked the ones in the validator sections to better match the flow of the information being provided.  

The how-prysm-works validator page doesn't really discuss the activation process, so it didn't make sense there..

**Comment by har00ga** [comment]
> The how-prysm-works validator page doesn't really discuss the activation process, so it didn't make sense there..

As mentioned the information needs to be thoroughly expanded on that page to include explainers for how ETH is deposited, the graphics will go a long way in that. There's a planned overhaul of the entire how-prysm-works section in the near future as it hasn't received a major revision since I originally authored it in early 2019, there spec is vastly more robust at this time & really needs the TLC

**Comment by wgknowles** [comment]
activating-a-validator pages & related graphics to be revisited later.

**Pull request merged**
